config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }  
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end

  root 'posts#index'

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  validates :content, presence: true;
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, presence: true, length: { maximum: 300 }

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy

  @@comment_limit = 4

  def last_comments
    comments.order("created_at ASC").last(@@comment_limit)
  end

  def self.comment_limit
    @@comment_limit
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validate :user_name_cannot_be_this

  acts_as_voter

  has_attached_file :image, styles: { medium: "640x", thumb: "160x160#" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  validates :bio, length: { maximum: 300 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy


  def user_name_cannot_be_this
    invalid_user_names = ['users', 'posts']
    if invalid_user_names.include? user_name
      errors.add(:user_name, "Invalid username")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def index
    @comments = @post.comments.order("created_at DESC")
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Your comment could not be submitted."
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :like, :edit, :update, :destroy]
  before_action :require_owner, only: [:edit, :update, :destroy]


  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created with caption: " + @post.caption
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post could not be created. Please check your input."
      render :new
    end
  end

  def show
  end

  def like
    if current_user.voted_for? @post
      like_success = @post.unliked_by current_user
    else
      like_success = @post.liked_by current_user
    end
    if like_success
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Your post has been updated!"
      redirect_to(post_path(@post))
    else
      flash.now[:alert] = "Update failed. Please check your input."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private
  def require_owner
    unless @post.user == current_user
      flash[:alert] = "Can't hax this"
      redirect_to root_path
    end
  end

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user
  before_action :require_owner, only: [:edit, :update]
  before_action :set_curr_image, only: [:show, :edit]

  def show
    @posts = @user.posts.order('created_at DESC').page params[:page]
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your profile has been updated!"
      redirect_to(profile_path(@user.user_name))
    else
      flash.now[:alert] = "Update failed. Please check your input."
      render :edit
    end
  end

  private
  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

  def require_owner
    unless @user == current_user
      flash[:alert] = "Can't hax this"
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:image, :bio)
  end

  def set_curr_image
    if @user.image.exists?
      @curr_image = @user.image.url(:thumb)
    else
      @curr_image = 'defaultprofilepic.jpg'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 2
    count_likers(votes)
  end

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name, profile_path(voter.user_name), class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end

  def count_likers(votes)
    vote_count = votes.size
    vote_count.to_s + ' likes'
  end

  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end

  def not_liked_post(post)
    return 'glyphicon-heart-empty' if current_user.voted_for? post
    'glyphicon-heart'
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comments.html.slim
- comments.each do |comment|
  #comment
    .user-name
      = link_to comment.user.user_name, profile_path(comment.user.user_name)
    .comment-content
      = comment.content
    - if comment.user == current_user
      = link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do
        span class="glyphicon glyphicon-remove delete-comment"

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comments', comments: [@comment], post: @post%>"); <%# there are brackets because comments should be an iterator%>
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render 'comments/comments', comments: @post.comments, post: @post %>");

app/views/comments/index.js.erb
$('#comments_<%= @post.id %>').html("<%= j render 'comments/comments', comments: @post.comments, post: @post %>");

app/views/layouts/_navbar.html.slim
.nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle Navigation
        span.icon-bar
        span.icon-bar
      .navbar-brand
        = link_to "MMBTI, much much better than instagram", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li
            = link_to "New Post", new_post_path
          li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          li
            = link_to "Login", new_user_session_path
          li
            = link_to "Register", new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Mmbti
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body id="#{controller_name}-#{action_name}"
    = render 'layouts/navbar'
    -flash.each do |name, msg|
      = content_tag :div, msg, class: [:alert, alert_for(name)]
    == yield

app/views/posts/_form.html.slim
.posts-wrapper
  .post
    .post-body
      .image-wrap
        - if @post.image.exists?
          - curr_image = @post.image.url(:medium)
        - else
          - curr_image = 'placeholder.jpg'
        = image_tag curr_image, id: 'image-preview', class: 'img-responsive', alt: ''
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              h4 Upload an image:
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, as: :text, label: false, placeholder: 'Add a caption', input_html: { class: 'form-control' }
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/posts/_likes.html.slim
.likes id="likes_#{ post.id }"
  = display_likes post

app/views/posts/_post.html.slim
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        = link_to post.user.user_name, profile_path(post.user.user_name)
      .time-ago
          = time_ago_in_words post.created_at
    .image.center-block
      = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
    .post-bottom
      = render 'posts/likes', post: post
      .caption
        .caption-content
          .user-name
            = link_to post.user.user_name, profile_path(post.user.user_name)
          = post.caption
        .comments id="comments_#{post.id}"
          - if post.comments.count > Post.comment_limit
            .load-all-comments
              = link_to "Load all #{post.comments.count} comments", post_comments_path(post), id:"link-text", remote: true
          - if post.comments
            = render 'comments/comments', comments: post.last_comments, post: post
    .comment-like-form.row
      = link_to like_post_path(post), remote: true do
        .like-button.col-sm-1
          span class="glyphicon #{liked_post post}" id="heart-post-#{ post.id }"
      .comment-form.col-sm-11
        = form_for([post, post.comments.build], remote: true) do |f|
          = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}", autocomplete: :off

app/views/posts/edit.html.slim
= render 'form'

.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  '  |
  = link_to "Cancel", posts_path

app/views/posts/index.html.slim
#posts-container
  = render @posts
#paginator
  = link_to_next_page @posts, 'Load More', :remote => true, class: 'btn btn-default', role: 'button'

app/views/posts/index.js.erb
$('#posts-container').append("<%= escape_javascript(render @posts) %>");
$('#paginator').html("<%= escape_javascript(link_to_next_page @posts, 'Load More', :remote => true, class: 'btn btn-default', role: 'button') %>");
if ($('#paginator').is(':empty')){
  $('#paginator').html("<p style='color:gray'>Nothing more to load<p>");
}

app/views/posts/like.js.erb
$('#heart-post-<%= @post.id %>').removeClass('<%= not_liked_post @post %>').addClass('<%= liked_post @post%>');
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.slim
= render 'form'

app/views/posts/show.html.slim
= render 'post', post: @post
.text-center.edit-links
  - if @post.user_id == current_user.id
    = link_to "Edit Post", edit_post_path(@post)
    '  |
    = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
    '  |
  = link_to "Cancel", posts_path

app/views/profiles/edit.html.slim
.posts-wrapper
  .post
    .post-body
      .image-wrap
        h4.text-center Change your profile image
        = image_tag @curr_image, id: 'image-preview', class: 'img-responsive', alt: ''
        = simple_form_for @user, html: { multipart: true }, url: update_profile_path(@user.user_name) do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              h4 Edit your bio
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :bio, as: :text, label: false, placeholder: 'Add a caption', input_html: { class: 'form-control' }
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/profiles/show.html.slim
.profile-wrapper
  .row
    .col-sm-4
      = image_tag @curr_image, class: 'img-responsive img-thumbnail', alt: ''
    .col-sm-8
      h1.profile-user-name
        = @user.user_name
      - if @user == current_user
        = link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'profile-edit-link btn', role: 'button'
      h4
        = @user.bio
#posts-container
  = render @posts
#paginator
  = link_to_next_page @posts, 'Load More', :remote => true, class: 'btn btn-default', role: 'button'

app/views/profiles/show.js.erb
$('#posts-container').append("<%= escape_javascript(render @posts) %>");
$('#paginator').html("<%= escape_javascript(link_to_next_page @posts, 'Load More', :remote => true, class: 'btn btn-default', role: 'button') %>");
if ($('#paginator').is(':empty')){
  $('#paginator').html("<p style='color:gray'>Nothing more to load<p>");
}